import './globals.css';
import { twMerge } from 'tailwind-merge';

import Image from 'next/image';
import { Montserrat } from 'next/font/google';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pokedex - Home Page',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header
          className={twMerge(
            montserrat.className,
            'w-full h-screen max-h-[600px] bg-radial from-[#AB0001] from-0% to-[#AB0001] to-100% relative'
          )}
        >
          <div className="flex flex-col h-full max-w-7xl mx-auto justify-center items-center">
            <div className="w-full pt-5">
              <Image
                alt="Pokemon Logo"
                src="/logo.svg"
                width={159}
                height={58}
              />
            </div>
            <div className="absolute bottom-1/2">
              <h2 className="text-white font-bold text-[6.4rem]">
                Who&apos;s that Pokémon?
              </h2>
              <p className="text-lg font-medium text-white text-center">
                The perfect guide for those who want to hunt Pokémon around the
                world.
              </p>
            </div>

            <div
              style={{ backgroundImage: "url('/red-bg-pattern.png')" }}
              className="bg-center bg-no-repeat bg-contain w-full mx-auto flex-1"
            />
            <Image
              className="absolute -bottom-[248px]"
              src="/red-pokeball.png"
              alt="Red Pokeball"
              width={800}
              height={520}
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
