import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Image from 'next/image';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header className="w-full border border-red-500 h-screen max-h-[600px] bg-radial from-[#AB0001] from-0% to-[#AB0001] to-100% ">
          <div className="flex flex-col h-full max-w-5xl mx-auto">
            <Image src="/logo.svg" alt="logo" width={159} height={58} />
            <div
              className="bg-center bg-no-repeat bg-contain w-full mx-auto flex-1"
              style={{ backgroundImage: "url('/bg.png')" }}
            ></div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
